newlistproject/listapp/urls.py
from django.urls import path
from . import views
app_name='listapp'
urlpatterns = [


path('',views.index,name='index'),
path('carlist/<int:carlist_id>/',views.detail, name='detail'),
path('add/',views.add_car,name='add_car'),
path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

newlistproject/newlistproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

 path('admin/', admin.site.urls),
path('',include("listapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

newlistproject/listapp/models.py
from django.db import models
from django.http import HttpResponse


# Create your models here.
class Carlist(models.Model):
    objects = None
    name=models.CharField(max_length=250)
    #mnum=models.IntegerField()
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
       return self.name

newlistproject/listapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from form import CarlistForm
from . models import Carlist

def index(request):
    carlist=Carlist.objects.all()
    context={
        'car_list':carlist
    }
    return render(request,'index.html',context)
def detail(request,carlist_id):
    carlist=Carlist.objects.get(id=carlist_id)
    return render(request,"detail.html",{'carlist':carlist})
def add_car(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc', )
        year=request.POST.get('year', )
        img=request.FILES['img']
        carlist=Carlist(name=name,desc=desc,year=year,img=img)
        carlist.save()
    return render(request,'add.html')
def update(request: object, id):
    carlist=Carlist.objects.get(id=id)
    form = CarlistForm()
    if request.method == 'POST' and  form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'carlist':carlist})
def delete(request,id):
    if request.method=="POST":
        carlist=Carlist.objects.get(id=id)
        carlist.delete()
        return redirect('/')
    return render(request,'delete.html')

newlistproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
    <input type="text" name="name" placeholder="Enter the car name:"><br>

    <input type="text" name="desc" placeholder="Enter the description:"><br>
    <input type="text" name="year" placeholder="Enter the year:"><br>
    <input type="file" name="img"><br>
    <input type="submit">


</form>
{% endblock %}

newlistproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    Benz-Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

newlistproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this data?
    <input type="submit">

</form>

newlistproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{carlist.img.url}}" width="400px;" height="300px;"><br>
        </div>


 <div class="container">
        {{carlist.name}}<br>
        {{carlist.desc}}<br>

       {{carlist.year}}<br>
<a class="btn btn-warning" href="{% url 'listapp:update' carlist.id %}">update</a><br>
<a class="btn btn-danger" href="{% url 'listapp:delete' carlist.id%}">Delete</a>
    </div>
    </div>
</div>
     {% endblock %}

newlistproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

newlistproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">

    <div class="row">
        {% for i in car_list %}
        <div class="col-md-3">
            <div class="card  margin:10px;">
               <img class="card-img-top" src="{{i.img.url}}" alt=""  width="200px;" height="250px;">
                 <div class="card-body">
                  <h5 class="card-title">{{i.name}}</h5>
                     <p class="card-text">{{i.desc}}</p>


                     <a href="{% url 'listapp:detail' i.id %}" class="btn btn-primary">Go In<br></a>

                 </div>
               </div>
        </div>
{% endfor %}

    </div>
    <br>
    <a href="{% url 'listapp:add_car'  %}" class="btn btn-success">Add new<br></a>
</div>

{% endblock %}